version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes: [data:/data/db]
    container_name: mongodb
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: naveen
    # - MONGO_INITDB_ROOT_USERNAME=naveen
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    image: backend-node
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg:
    ports:
      - "80:80"
    volumes: [logs:/app/logs, ./backend:/app, /app/node_modules]
    container_name: backend-api
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: frontend-react
    ports:
      - "3000:3000"
    volumes: [./frontend/src:/app/src]
    container_name: frontend-app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
